version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: makesense
      MYSQL_USER: testDB
      MYSQL_PASSWORD: testDB
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - testDB:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  testDB: